// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * AccessEnvironment
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "AccessEnvironment": (arg1) => {
        return window.go.main.App.AccessEnvironment(arg1);
      },
      /**
       * AccessLogs
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "AccessLogs": (arg1) => {
        return window.go.main.App.AccessLogs(arg1);
      },
      /**
       * AddEnvironment
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @param {string} arg6 - Go Type: string
       * @param {string} arg7 - Go Type: string
       * @returns {Promise<boolean|string>}  - Go Type: bool
       */
      "AddEnvironment": (arg1, arg2, arg3, arg4, arg5, arg6, arg7) => {
        return window.go.main.App.AddEnvironment(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
      },
      /**
       * AddImage
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<void>} 
       */
      "AddImage": (arg1, arg2) => {
        return window.go.main.App.AddImage(arg1, arg2);
      },
      /**
       * ChangeEnvironment
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @param {string} arg6 - Go Type: string
       * @param {string} arg7 - Go Type: string
       * @param {string} arg8 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "ChangeEnvironment": (arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => {
        return window.go.main.App.ChangeEnvironment(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
      },
      /**
       * ChangeImage
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "ChangeImage": (arg1, arg2, arg3) => {
        return window.go.main.App.ChangeImage(arg1, arg2, arg3);
      },
      /**
       * GetEnvironment
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<models.Environment>}  - Go Type: main.Environment
       */
      "GetEnvironment": (arg1) => {
        return window.go.main.App.GetEnvironment(arg1);
      },
      /**
       * GetEnvironments
       * @returns {Promise<Array<models.EnvInJSON>|boolean>}  - Go Type: []main.EnvInJSON
       */
      "GetEnvironments": () => {
        return window.go.main.App.GetEnvironments();
      },
      /**
       * GetImage
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<models.Image>}  - Go Type: main.Image
       */
      "GetImage": (arg1) => {
        return window.go.main.App.GetImage(arg1);
      },
      /**
       * GetImages
       * @returns {Promise<Array<models.ImageInJSON>|boolean>}  - Go Type: []main.ImageInJSON
       */
      "GetImages": () => {
        return window.go.main.App.GetImages();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * RemoveEnvironment
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "RemoveEnvironment": (arg1) => {
        return window.go.main.App.RemoveEnvironment(arg1);
      },
      /**
       * RemoveImage
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RemoveImage": (arg1) => {
        return window.go.main.App.RemoveImage(arg1);
      },
      /**
       * StartEnv
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "StartEnv": (arg1) => {
        return window.go.main.App.StartEnv(arg1);
      },
      /**
       * StopEnv
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "StopEnv": (arg1) => {
        return window.go.main.App.StopEnv(arg1);
      },
      /**
       * Test
       * @returns {Promise<models.Table>}  - Go Type: *main.Table
       */
      "Test": () => {
        return window.go.main.App.Test();
      },
    },
  },

};
export default go;
